(() => {
    const language = (chrome.i18n.getUILanguage() || navigator.language || 'en').toLowerCase();
    const locale = language.startsWith('uk') ? 'uk' : language.startsWith('ru') ? 'ru' : 'en';
    document.documentElement.lang = locale;
    document.title = locale === 'uk' ? 'Конфіденційність — Midvea Shelter' : locale === 'ru' ? 'Конфиденциальность — Midvea Shelter' : 'Privacy — Midvea Shelter';
    const content = {
        en: `<h1>Privacy Policy</h1><p class="date">Effective August 15, 2026</p><p>Midvea Shelter is a local-first new tab extension. We do not sell user data or use hidden analytics.</p><h2>Data used</h2><ul><li>Chrome bookmarks, to display and manage bookmarks and folders chosen by the user;</li><li>Chrome local storage, for settings, notes, appearance, backgrounds, and cache;</li><li>location, only after user permission, to request local weather;</li><li>network requests to the selected search provider, background sources, suggestion services, and Open-Meteo.</li></ul><h2>Transfer and storage</h2><p>Settings and notes stay in Chrome storage on the user’s device. External services receive only the data required for a feature selected by the user.</p><h2>Data control</h2><p>Users can change or delete bookmarks, notes, and settings in the extension, or remove the extension and its local data through Chrome.</p><h2>Contact</h2><p>Current developer support details are provided on the extension’s Chrome Web Store listing.</p>`,
        ru: `<h1>Политика конфиденциальности</h1><p class="date">Редакция от 15 августа 2026 года</p><p>Midvea Shelter — расширение новой вкладки, спроектированное по принципу local-first. Мы не продаём пользовательские данные и не используем скрытую аналитику.</p><h2>Какие данные используются</h2><ul><li>закладки Chrome — для отображения и управления выбранными пользователем закладками и папками;</li><li>локальное хранилище Chrome — для настроек, заметок, оформления, фонов и кэша;</li><li>геолокация — только после разрешения пользователя, чтобы запросить погоду;</li><li>сетевые запросы — к выбранному поисковику, источникам обоев, подсказкам и Open-Meteo.</li></ul><h2>Передача и хранение</h2><p>Настройки и заметки сохраняются средствами Chrome на устройстве пользователя. Внешнему сервису передаются только данные, необходимые для выбранной функции.</p><h2>Управление данными</h2><p>Пользователь может изменить или удалить закладки, заметки и настройки через интерфейс расширения либо удалить расширение и его локальные данные средствами Chrome.</p><h2>Контакты</h2><p>Актуальные контакты разработчика указаны на странице расширения в Chrome Web Store.</p>`,
        uk: `<h1>Політика конфіденційності</h1><p class="date">Редакція від 15 серпня 2026 року</p><p>Midvea Shelter — розширення нової вкладки, створене за принципом local-first. Ми не продаємо дані користувачів і не використовуємо приховану аналітику.</p><h2>Які дані використовуються</h2><ul><li>закладки Chrome — для показу та керування обраними користувачем закладками й папками;</li><li>локальне сховище Chrome — для налаштувань, нотаток, оформлення, фонів і кешу;</li><li>геолокація — лише після дозволу користувача, щоб отримати місцеву погоду;</li><li>мережеві запити — до обраного пошуковика, джерел фонів, сервісів підказок та Open-Meteo.</li></ul><h2>Передавання та зберігання</h2><p>Налаштування й нотатки зберігаються засобами Chrome на пристрої користувача. Зовнішній сервіс отримує лише дані, потрібні для обраної функції.</p><h2>Керування даними</h2><p>Користувач може змінити або видалити закладки, нотатки й налаштування в розширенні або видалити розширення та його локальні дані засобами Chrome.</p><h2>Контакти</h2><p>Актуальні контакти розробника наведені на сторінці розширення в Chrome Web Store.</p>`
    };
    document.getElementById('privacy-content').innerHTML = content[locale];
})();
